version: "3.8"
services:
  db:
    build:
      context: ./sql
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    container_name: db
    env_file:
      - ".env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-volume:/var/lib/postgresql/data
  auth-service:
    build:
      args:
        - USER_ID=1000
        - GROUP_ID=1000
        - USERNAME=richard
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth_service
    env_file:
      - ".env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - ./auth:/app
    links:
      - db
  todo-service:
    build:
      args:
        - USER_ID=1000
        - GROUP_ID=1000
        - USERNAME=richard
      context: ./todo
      dockerfile: Dockerfile
    container_name: todo_service
    env_file:
      - ".env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - "7000:7000"
    depends_on:
      - db
    volumes:
      - ./todo:/app
    links:
      - db
  auth-proxy:
    build:
      context: ./web
      dockerfile: Dockerfile.envoy_auth
    ports:
      - "1000:1000"
  todo-proxy:
    build:
      context: ./web
      dockerfile: Dockerfile.envoy_todo
    ports:
      - "2000:2000"
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    depends_on:
      - auth-proxy
      - todo-proxy
      - auth-service
      - todo-service
    tty: true
    volumes:
      - /app/node_modules
      - ./web:/app
volumes:
  db-volume:
    driver: local
