version: "3.8"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    container_name: db
    env_file:
      - ".env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-volume:/var/lib/postgresql/data
  main:
    build:
      context: ./main-service
      dockerfile: Dockerfile
    container_name: main_service
    env_file:
      - ".env"
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./main-service:/app
    links:
      - db
  # auth-service:
  #   build:
  #     args:
  #       - USER_ID=1000
  #       - GROUP_ID=1000
  #       - USERNAME=richard
  #     context: ./auth
  #     dockerfile: Dockerfile
  #   container_name: auth_service
  #   env_file:
  #     - ".env"
  #   ports:
  #     - "9000:9000"
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./auth:/app
  #   links:
  #     - db
volumes:
  db-volume:
    driver: local